#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RepeatTakers.Resource", IsApplication=true)]

namespace RepeatTakers
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int i112 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int i29 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int i38 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int scales = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tort = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int RepeatLogo = 2131034127;
			
			// aapt resource value: 0x7f050018
			public const int Torts = 2131034136;
			
			// aapt resource value: 0x7f050001
			public const int allButton = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int button1 = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int constitutionalLawButton = 2131034133;
			
			// aapt resource value: 0x7f050002
			public const int constitutionallawButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int contractsButton = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int criminalLawButton = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int criminalProcedureButton = 2131034135;
			
			// aapt resource value: 0x7f050004
			public const int criminallawButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int criminalprocedureButton = 2131034117;
			
			// aapt resource value: 0x7f050010
			public const int demoButton = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int evidenceButton = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int flashcardsButton = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int fragment1 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int frameLayout1 = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int graphicalexamplesButton = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int imageButton1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout1 = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int loginButton = 2131034129;
			
			// aapt resource value: 0x7f05001b
			public const int nextBtn = 2131034139;
			
			// aapt resource value: 0x7f050014
			public const int notesButton = 2131034132;
			
			// aapt resource value: 0x7f05001a
			public const int previousBtn = 2131034138;
			
			// aapt resource value: 0x7f050007
			public const int propertyButton = 2131034119;
			
			// aapt resource value: 0x7f050019
			public const int studyImageView = 2131034137;
			
			// aapt resource value: 0x7f05000e
			public const int textView1 = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int tortsButton = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FlashCards = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageUpload = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SIView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StudyImageView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
